api/urls.py
from django.urls import path
from .views import PostListView, PostCreateView, PostEditView, PostDetailView

app_name='api'
urlpatterns = [
    path('posts/', PostListView.as_view(), name='post_list'),
    path('post_create/', PostCreateView.as_view(), name='create_post'),
    path('post_edit/<int:pk>/', PostEditView.as_view(), name='post_edit'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail')
]

post/urls.py
from django.urls import path
from .views import PostCreateView,  PostListByCategoryView, PostListView, PostSearchView, PostDetailView

app_name='post'

urlpatterns = [
    path('create_post/', PostCreateView.as_view(), name='create_post'),
    path('category/<str:category_name>/', PostListByCategoryView.as_view(), name='posts_by_category'),
    path('', PostListView.as_view(), name='post_list'),
    path('search/', PostSearchView.as_view(), name='post_search'),
    path('<int:pk>/', PostDetailView.as_view(), name='detail'),
]

user/urls.py
from django.urls import path
from .views import HomeView, RegisterView,  VerificationView, ChoosePostView, ProfileView, PostEditView
from django.contrib.auth.views import LogoutView, LoginView

app_name = 'user'
urlpatterns = [
    path('home', HomeView.as_view(), name='home'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/', VerificationView.as_view(), name='verify_code'),
    path('choose/<int:post_pk>/', ChoosePostView.as_view(), name='choose_post'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('<int:pk>/edit/', PostEditView.as_view(), name='post_edit'),
]

volunteer/urls.py
from tkinter.font import names

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace='user')),
    path('posts/', include('post.urls', namespace='post')),
    path('charity/', include('charityGeorgia.urls', namespace='charityGeorgia')),
    path('api/', include('api.urls', namespace='api'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
from django.db import models
from django.conf import settings
from datetime import datetime


class Category(models.Model):
    name=models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=20, blank=True)
    description = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    location = models.CharField(max_length=255)
    picture = models.ImageField('picture',upload_to='post_pictures/', null=True, blank=True,  default='default_images/default_picture.png')
    deadline_date = models.DateField(null=True, blank=True)
    deadline_time = models.TimeField(null=True, blank=True)
    custom_input_1 = models.CharField(max_length=255, blank=True, null=True)  # Add this line
    custom_input_2 = models.CharField(max_length=255, blank=True, null=True)  # Add this line
    prefer = models.CharField(max_length=255, blank=True, null=True)
    categories = models.ManyToManyField(Category, related_name='posts', blank=True)
    completed = models.BooleanField(default=False)

    deadline = models.DateTimeField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.deadline_date and self.deadline_time:
            self.deadline = datetime.combine(self.deadline_date, self.deadline_time)
        super(Post, self).save(*args, **kwargs)


    def __str__(self):
        return self.title or 'no title'

post/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    PREFER_CHOICES = [
        ('სისხლი', 'სისხლი'),
        ('მოხუცი', 'მოხუცი'),
        ('ბავშვი', 'ბავშვი'),
        ('შშმ პირი', 'შშმ პირი'),
        ('გარემო', 'გარემო'),
        ('საკვები', 'საკვები'),
    ]



    prefer = forms.MultipleChoiceField(
        choices=PREFER_CHOICES,
        widget=forms.CheckboxSelectMultiple
    )
    title = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'სათაური', 'class': 'form-control'})
    )
    custom_input_1 = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'input-text',}))
    custom_input_2 = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'input-text'}))

    deadline_date = forms.DateField(
        widget=forms.DateInput(attrs={
            'type': 'date',
            'class': 'form-control',
            'id': 'deadline-date',
        })
    )
    deadline_time = forms.TimeField(
        required=False,
        widget=forms.TimeInput(attrs={
            'type': 'time',
            'class': 'form-control',
            'id': 'deadline-time',
        })
    )
    location = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control', 'style': 'color:#660066;', 'placeholder': 'ქალაქი'})
    )
    description = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'აღწერა',
        'class': 'input-textarea',
        'id': 'description',
        'style': 'width: 100%; height: 100px;'
    }))

    picture = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={'class': 'form-control', 'style': 'color:#660066;', 'accept': 'image/*'})
    )


    class Meta:
        model = Post
        fields = ['title', 'description', 'prefer', 'deadline_date', 'deadline_time', 'location',  'picture', 'custom_input_1', 'custom_input_2',]

post/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, TemplateView, DetailView, ListView
from django.urls import reverse_lazy
from django.core.cache import cache
from django.db.models import Q, Prefetch
from .forms import PostForm
from .models import Post, Category


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'create_post.html'
    success_url = reverse_lazy('post:post_list')

    def form_valid(self, form):
        if not self.request.user.is_authenticated:
            return redirect('user:login')

        form.instance.author = self.request.user
        selected_preferences =form.cleaned_data.get('prefer', [])
        existing_categories = Category.objects.filter(name__in=selected_preferences)
        existing_category_names = set(existing_categories.values_list('name', flat=True))

        categories_to_create = [
            Category(name=name) for name in selected_preferences
            if name not in existing_category_names
        ]
        if categories_to_create:
            Category.objects.bulk_create(categories_to_create)

        categories_to_assign = Category.objects.filter(name__in=selected_preferences)

        post = form.save(commit=False)
        post.save()

        post.categories.set(categories_to_assign)

        custom_input_1 = self.request.POST.get('custom_input_1', '') or None
        custom_input_2 = self.request.POST.get('custom_input_2', '') or None


        if not form.cleaned_data.get('picture'):
            form.instance.picture = 'default_images/default_picture.png'
        post.save()

        return super().form_valid(form)


class PostListByCategoryView(ListView):
    model = Post
    template_name = 'posts.html'
    context_object_name = 'posts'


    def get_queryset(self):
        category_name = self.kwargs['category_name']
        return Post.objects.filter(categories__name=category_name).prefetch_related('categories').order_by('-created_at')


class PostListView(ListView):
    model = Post
    template_name = 'posts.html'
    context_object_name = 'posts'
    paginate_by = 12

    def get_queryset(self):
        return Post.objects.all().order_by('-created_at').prefetch_related('categories', 'author')


class PostSearchView(ListView):
    model = Post
    template_name = "posts.html"
    context_object_name = "posts"

    def get_queryset(self):
        query = self.request.GET.get('q', '')
        cache_key = f"search_{query}"
        cached_results = cache.get(cache_key)

        if cached_results:
            return cached_results

        filters = (
            Q(title__icontains=query) |
            Q(description__icontains=query) |
            Q(location__icontains=query) |
            Q(custom_input_1__icontains=query) |
            Q(custom_input_2__icontains=query) |
            Q(author__username__icontains=query) |
            Q(categories__name__icontains=query)
        )
        queryset = Post.objects.filter(filters).distinct().select_related('author').prefetch_related('categories')
        cache.set(cache_key, queryset, timeout=3600)
        return queryset


class PostDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'
    context_object_name = 'post'

templates/change_email.html
<div class="user-info">
    <br>
    <div class="user_email">
        <h2>Change Email</h2>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Save Changes</button>
        </form>
    </div>
</div>

templates/charity_page11.html
<h1> {{ charity_data.name }}</h1>
<p> {{ charity_data.scraped_text }}</p>
<a href="{{ charity_data.website }}">visit website</a>

templates/create_post.html
<!--{% load static %}-->
<!--<!DOCTYPE html>-->
<!--<html>-->
<!--<head>-->
<!--  <title>WeHelp</title>-->
<!--  <link rel="stylesheet" href="{% static 'assets/css/create_post_style.css' %}">-->
<!--</head>-->
<!--<body>-->
<!--  <div class="group">-->
<!--    <header class="header">-->
<!--      <h1 id="title" class="text-center"></h1>-->
<!--      <p id="description" class="description text-center"></p>-->
<!--    </header>-->
<!--    <form method="post" action="{% url 'user:home'%}" enctype="multipart/form-data" id="survey-form">-->
<!--        {% csrf_token %}-->

<!--        <div class="form-group">-->
<!--            <strong>-->
<!--              <label id="text" style="color:#660066; font-size:20px;">სათაური <span class="clue" style="color:#660066;">(optional)</span></label><br>-->
<!--            </strong>-->
<!--            {{ form.title }}-->
<!--        </div>-->

<!--        <div class="form-group">-->
<!--    <p style="color:#660066">აირჩიეთ:</p>-->
<!--    <div class="form-group-checkboxes">-->
<!--        {{ form.prefer }} &lt;!&ndash; Render the entire prefer field here &ndash;&gt;-->
<!--    </div>-->
<!--</div>-->

<!--        <div class="form-group">-->
<!--          <p style="color:#660066;">Deadline:</p>-->
<!--          <label for="deadline-date" style="color:#660066">თარიღი:</label><br>-->
<!--          {{ form.deadline_date }}<br><br>-->
<!--          <label for="deadline-time" style="color:#660066">დრო: <span class="clue" style="color:#660066;">(optional)</span></label><br>-->
<!--          {{ form.deadline_time }}-->
<!--        </div>-->

<!--        <div class="form-group">-->
<!--          <p style="color:#660066;">ლოკაცია:</p>-->
<!--          {{ form.location }}-->
<!--        </div>-->

<!--        <div class="form-group">-->
<!--          <p style="color:#660066;">აღწერა:</p>-->
<!--          {{ form.description }}-->
<!--        </div>-->

<!--        <div class="form-group">-->
<!--          <p style="color:#660066;">ფოტოს დამატება: <span class="clue" style="color:#660066;">(optional)</span></p>-->
<!--          {{ form.picture}}-->
<!--        </div>-->

<!--        <button type="submit" style="color:#660066;" id="submit" value="submit" class="submit-button">პოსტის განთავსება</button>-->
<!--    </form>-->
<!--  </div>-->
<!--</body>-->
<!--</html>-->



{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>WeHelp</title>
  <link rel="stylesheet" href="{% static 'assets/css/create_post_style.css' %}">
</head>
  <body>
  <div class="logo">
                                    <a href="{% url 'user:home' %}"><img src="{% static 'assets/img/logo/logo.png' %}" alt=""></a>
                                </div>
    <div class="group">
      <header class="header">
        <h1 id="title" class="text-center"></h1>
        <p id="description" class="description text-center"></p>
      </header>
      <form method="post" action="{% url 'post:create_post' %}" enctype="multipart/form-data" id="survey-form">
          {% csrf_token %}
         <div class="form-group">
          <!-- Render the form fields -->
        <div class="form-group">
            <strong>
              <label  id="text" style="color:#660066; font-size:20px;">სათაური <span class="clue" style="color:#660066;">(optional) <br></span></label><br>
            </strong>
            {{ form.title }}
        </div>

<div class="form-group">
    <p style="color:#660066;">აირჩიეთ:<span class="clue"> </span></p>
    <div class="form-group-checkboxes">
        {% for value, label in form.prefer.field.choices %}
            <label>
                <input name="prefer" type="checkbox" value="{{ value }}" class="input-checkbox" {% if value in form.prefer.value %}checked{% endif %}/> {{ label }}
            </label><br><br>
        {% endfor %}

        <!-- Custom input fields -->
 <label for="custom_input_1">
    <input type="checkbox" name="custom_input_1" value="True" {% if form.custom_input_1.value %}checked{% endif %}>

</label><br><br>

<!-- Input for custom_input_1 -->
<label for="custom_input_1">
    <input type="text" name="custom_input_1" style="margin-left:-210px;" value="{{ form.custom_input_1.value|default:'' }}">
</label><br><br>

<!-- Checkbox for custom_input_2 -->
<label for="custom_input_2">
    <input type="checkbox" name="custom_input_2" value="True" {% if form.custom_input_2.value %}checked{% endif %}>

</label><br><br>

<!-- Input for custom_input_2 -->
<label for="custom_input_2">
    <input type="text" name="custom_input_2" style="margin-left:-210px;" value="{{ form.custom_input_2.value|default:'' }}">
</label><br><br>
        </div>
    </div>
<div class="form-group">
        <p style="color:#660066;">Deadline:</p>

        <label for="deadline-date" style="color:#660066;">თარიღი:</label><br>
        {{ form.deadline_date }}<br><br>

        <label for="deadline-time" style="color:#660066;">დრო: <span class="clue" style="color:#660066;">(optional)</span></label><br>
        {{ form.deadline_time }}
    </div>


      <div class="form-group">
    <p style="color:#660066;">ლოკაცია:</p>
    {{ form.location }}
</div>

        <div class="form-group">
        <p style="color:#660066;">აღწერა:</p>
        {{ form.description }}
    </div>

          <div class="form-group">
              <p style="color:#660066;">ფოტოს დამატება: <span class="clue" style="color:#660066;">(optional)</span></p>
              {{ form.picture }}
          </div>

          <button type="submit" style="color:#660066;" id="submit" value="submit" class="submit-button">პოსტის განთავსება</button>
         </div>
      </form>
    </div>

</body>
</html>

templates/new_registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>რეგისტრაცია</title>
  <link rel="stylesheet" href="{% static 'assets/css/registration_style.css' %}">

</head>
<body>
   <div class="logo">
                                    <a href="{% url 'user:home' %}"><img src="{% static 'assets/img/logo/logo.png' %}" alt=""></a>
                                </div>

  <div class="container">
    <!-- Title section -->
    <div class="title">რეგისტრაცია</div>
    <div class="content">
      <!-- Registration form -->
      <form id="registerForm"  method="POST" action="" >
        {% csrf_token %}


        <div class="user-details">
          <!-- Input for Full Name -->
  
          <!-- Input for Username -->
          <div class="input-box">
            <span class="details"></span>
            <input type="text" id="username" name='username' placeholder="Username" required >
            {% if form.username.errors %}
                    <div class="error-message">
                        {% for error in form.username.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}

          </div>
          <div class="input-box">
            <span class="details"></span>
            <input type="password" id="password" name="password" placeholder="პაროლი" required>
            {% if form.password.errors %}
                    <div class="error-message">
                        {% for error in form.password.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}

          </div>
          <!-- Input for Email -->
          <div class="input-box">
            <span class="details"></span>
            <input type="email" id="email" name="email" placeholder="Email" required>
            {% if form.email.errors %}
                    <div class="error-message">
                        {% for error in form.email.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
          </div>

          <div class="input-box">
            <span class="details"></span>
            <input type="password" id="confirm_password" name="confirm_password" placeholder="დაადასტურეთ პაროლი" required>
            {% if form.confirm_password.errors %}
                    <div class="error-message">
                        {% for error in form.confirm_password.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}

          </div>
          <!-- Input for Phone Number -->
          <div class="input-box">
            <span class="details"></span>
            <input type="text" id="phone_number" name="phone_number" placeholder="ტელეფონის ნომერი" required>
            {% if form.phone_number.errors %}
                    <div class="error-message">
                        {% for error in form.phone_number.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}

          </div>
          <!-- Input for Password -->

          <!-- Input for Confirm Password -->

        </div>

        <!-- Submit button -->
        <div class="button">
          <input type="submit" value="რეგისტრაცია">
        </div>
      </form>
    </div>
  </div>
</body>
</html>

templates/profile.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>WeHelp</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--    <link rel="manifest" href="site.webmanifest">-->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/progressbar_barfiller.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animated-headline.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/profile_style.css' %}">

</head>

<body>
    <!-- ? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="{% static 'assets/img/logo/loder.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start -->

    <!-- Header Start -->
    <div class="header-area header-transparent">
        <div class="main-header">
            <div class="header-bottom header-sticky">
                <div class="container-fluid">
                    <div class="row align-items-center" >
                        <!-- Logo -->
                        <div class="c">
                            <div class="logo">
                                <a href="{% url 'user:home' %}"><img src="{% static 'assets/img/logo/logo.png' %}" alt=""></a>
                            </div>
                        </div>
                        <div class="col-xl-10 col-lg-10">
                            <div class="menu-wrapper d-flex align-items-center justify-content-end">
                                <!-- Main-menu -->
                                <div class="main-menu d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li class="active"><a href="{% url 'user:home' %}" style="font-size: 19px; color: white; text-decoration: none;" onmouseover="this.style.color='#FFFF00'" onmouseout="this.style.color='white'">მთავარი</a></li>
                                            <li><a href="{% url 'post:post_list' %}" style="font-size: 18px; color: white; text-decoration: none;" onmouseover="this.style.color='#FFFF00'" onmouseout="this.style.color='white'">ვის შემიძლია დავეხმარო?</a></li>
                                            <li>
                                                {% if user.is_authenticated %}
                                                    <a href="{% url 'post:create_post' %}" style="font-size: 18px; color: white; text-decoration: none;" onmouseover="this.style.color='#FFFF00'" onmouseout="this.style.color='white'">პოსტის განთავსება</a>
                                                {% else %}
                                                    <a href="{% url 'user:login' %}" style="font-size: 18px; color: white; text-decoration: none;" onmouseover="this.style.color='#FFFF00'" onmouseout="this.style.color='white'">პოსტის განთავსება</a>
                                                {% endif %}
                                            </li>
                                            <li class="button-header">
                                                {% if user.is_authenticated %}
                                                    <form action="{% url 'user:logout' %}" method="post">
                                                        {% csrf_token %}
                                                        <button type="submit" class="btn btn3">გამოსვლა</button>
                                                    </form>
                                                {% else %}
                                                    <a href="{% url 'user:login' %}" class="btn btn3">შესვლა</a>
                                                {% endif %}
                                            </li>
                                            <li class="profile-icon-item">
                                                {% if user.is_authenticated %}
                                                    <a href="{% url 'user:profile' %}"  class="profile-icon">
                                                        <i class="fas fa-user-circle"></i>
                                                    </a>
                                                {% endif %}
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->

    <main>
        <div class="test">
        <!--? slider Area Start-->
        <div class="main-container">
            <!-- Info container -->


            <!-- Sidebar Menu -->
           <!-- Sidebar Menu -->
<div class="categories-sidebar_custom">
    <ul class="categories-list">
        <li><a href="?category=information"><i class="fas fa-heart"></i>თქვენი ინფორმაცია</a></li>
        <li><a href="?category=user_posts"><i class="fas fa-heart"></i> თქვენი პოსტები</a></li>
        <li><a href="?category=chosen_posts"><i class="fas fa-heart"></i> თქვენი არჩეული პოსტები</a></li>

    </ul>
</div>


<!-- Info Container -->
<div class="info-container" style="color:black;">
    <h1>

        {% if category == 'user_posts' %}

            თქვენი პოსტები <br>
        {% elif category == 'chosen_posts' %}
            თქვენი არჩეული პოსტები <br>
        {% else %}
            თქვენი ინფორმაცია
          <br>
        {% endif %}
    </h1>
 {% if not category or category == 'information' %}
                    <!-- Display User Information -->
                    <div class="user-info" >
                        <br>
                        <div class="user_email">
                        <p style="color:white;"><strong>Email:</strong> {{ user.email }}</p>
<!--                        <button > შეცვლა </button>-->
                            </div>

                        <p style="color:white;"><strong>Username:</strong> {{ user.username }}</p>
                        <p style="color:white;">ტელეფონის ნომერი: {{ user.phone_number }}</p>
                    </div>
{% endif %}
    {% if category == 'user_posts' or category == 'chosen_posts' %}
    <!-- Loop through the posts and display them -->
    {% for post in posts %}
    <br>
        <div class="post-item">
            <h2 style="color:white;">
    <a href="{% url 'post:detail' post.id %}" style="color:white; text-decoration:none;">
        {{ post.title }}
    </a>
</h2>
            <p style="display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; text-overflow: ellipsis; color:white;">{{ post.description }}</p>  <!-- Display the post description -->
            <p style="color:white;">ლოკაცია: {{ post.location }}<br>
                        {% if post.deadline_date %}
                        <p style="color:white;">Deadline: {{ post.deadline_date|date:"F j, Y" }}
                        {% if post.deadline_time %}
                            / {{ post.deadline_time|time:"g:i a" }}
                        {% endif %}
                        </p>
                    {% else %}
                        <p>No deadline set</p>
                    {% endif %}
            {% if category == 'user_posts' %}
                <!-- Show buttons only when 'user_posts' category is selected -->
            <form method="post" action="{% url 'user:profile' %}">
                {% csrf_token %}
                  <input type="hidden" name="post_id" value="{{ post.id }}">
                <input type="hidden" name="action" value="delete">
                <div class="buttons-container">

                    <button class="noselect">
                        <span class="text">წაშლა</span>
                        <span class="icon">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                <path d="M24 20.188l-8.315-8.209 8.2-8.282-3.697-3.697-8.212 8.318-8.31-8.203-3.666 3.666 8.321 8.24-8.206 8.313 3.666 3.666 8.237-8.318 8.285 8.203z"></path>
                            </svg>
                        </span>
                    </button>


                </div>
                </form>
             <form method="get" action="{% url 'user:post_edit' post.id %}">
    <button type="submit" class="button2">
        რედაქტირება
    </button>
</form>
              <form method="post" action="">
            {% csrf_token %}
            <input type="hidden" name="post_id" value="{{ post.id }}">
            <input type="hidden" name="action" value="mark_completed">

            <button
                type="submit"
                style="display: flex; justify-content: center; align-items: center; text-align: center; background-color: {% if post.completed %}grey{% else %}#FF66FF{% endif %}; color: white;"
                {% if post.completed %}disabled{% endif %}
            >
                {% if post.completed %}დასრულებული{% else %}მონიშნეთ როგორც დასრულებული{% endif %}
            </button>
        </form>
            {% endif %}
        </div>
     <div class="post-divider"></div>
    {% empty %}
        <p>თქვენ არ გაქვთ პოსტები.</p>
    {% endfor %}
    {% endif %}




</div>
        </div>
        </div>
    </main>



<!-- JS here -->
<script src="{% static 'assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
<!-- Jquery, Popper, Bootstrap -->
<script src="{% static 'assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'assets/js/popper.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<!-- Jquery Mobile Menu -->
<script src="{% static 'assets/js/jquery.slicknav.min.js' %}"></script>

<!-- Jquery Slick , Owl-Carousel Plugins -->
<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'assets/js/slick.min.js' %}"></script>
<!-- One Page, Animated-HeadLin -->
<script src="{% static 'assets/js/wow.min.js' %}"></script>
<script src="{% static 'assets/js/animated.headline.js' %}"></script>
<script src="{% static 'assets/js/jquery.magnific-popup.js' %}"></script>

<!-- Date Picker -->
<script src="{% static 'assets/js/gijgo.min.js' %}"></script>
<!-- Nice-select, sticky -->
<script src="{% static 'assets/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.sticky.js' %}"></script>
<!-- Progress -->
<script src="{% static 'assets/js/jquery.barfiller.js' %}"></script>

<!-- counter , waypoint,Hover Direction -->
<script src="{% static 'assets/js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'assets/js/waypoints.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'assets/js/hover-direction-snake.min.js' %}"></script>

<!-- contact js -->
<script src="{% static 'assets/js/contact.js' %}"></script>
<script src="{% static 'assets/js/jquery.form.js' %}"></script>
<script src="{% static 'assets/js/jquery.validate.min.js' %}"></script>
<script src="{% static 'assets/js/mail-script.js' %}"></script>
<script src="{% static 'assets/js/jquery.ajaxchimp.min.js' %}"></script>

<!-- Jquery Plugins, main Jquery -->
<script src="{% static 'assets/js/plugins.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>